### ISSUE TITLE
error when running _ppo_mp.py

### ISSUE THREAD

**Issue by kotaxyz** [yul85/movingcam#11]
@yul85  i get this error when running the script hurdle_ppo_mp.py

(venv) (mocap) genesis@DESKTOP-N3L45SD:~/github/mocap/movingcam/control/hurdle$ python hurdle_ppo_mp.py
/home/genesis/github/mocap/movingcam/venv/lib/python3.8/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/home/genesis/github/mocap/movingcam/venv/lib/python3.8/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/home/genesis/github/mocap/movingcam/venv/lib/python3.8/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/home/genesis/github/mocap/movingcam/venv/lib/python3.8/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/home/genesis/github/mocap/movingcam/venv/lib/python3.8/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/home/genesis/github/mocap/movingcam/venv/lib/python3.8/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/home/genesis/github/mocap/movingcam/venv/lib/python3.8/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/home/genesis/github/mocap/movingcam/venv/lib/python3.8/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/home/genesis/github/mocap/movingcam/venv/lib/python3.8/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/home/genesis/github/mocap/movingcam/venv/lib/python3.8/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/home/genesis/github/mocap/movingcam/venv/lib/python3.8/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/home/genesis/github/mocap/movingcam/venv/lib/python3.8/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/home/genesis/github/mocap/movingcam/venv/lib/python3.8/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/home/genesis/github/mocap/movingcam/venv/lib/python3.8/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/home/genesis/github/mocap/movingcam/venv/lib/python3.8/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/home/genesis/github/mocap/movingcam/venv/lib/python3.8/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/home/genesis/github/mocap/movingcam/venv/lib/python3.8/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
hurdle_ppo_mp.py:365: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:261.)
  a_dist, v = self.model(torch.tensor(states).float())
Process Process-5:
Process Process-7:
Process Process-10:
Process Process-15:
Process Process-16:
Process Process-3:
Process Process-11:
Process Process-8:
Process Process-9:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "hurdle_ppo_mp.py", line 180, in worker
    state, reward, is_done, _ = env.step(action)
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 395, in step
    return tuple([self.state(), self.reward(), self.is_done(), {}])
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 220, in reward
    up_angle_hat = self.up_angle_list[self.current_frame]
  File "hurdle_ppo_mp.py", line 180, in worker
    state, reward, is_done, _ = env.step(action)
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 395, in step
    return tuple([self.state(), self.reward(), self.is_done(), {}])
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 220, in reward
    up_angle_hat = self.up_angle_list[self.current_frame]
IndexError: list index out of range
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "hurdle_ppo_mp.py", line 180, in worker
    state, reward, is_done, _ = env.step(action)
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 395, in step
    return tuple([self.state(), self.reward(), self.is_done(), {}])
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 220, in reward
    up_angle_hat = self.up_angle_list[self.current_frame]
IndexError: list index out of range
Process Process-13:
Traceback (most recent call last):
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "hurdle_ppo_mp.py", line 180, in worker
    state, reward, is_done, _ = env.step(action)
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 395, in step
    return tuple([self.state(), self.reward(), self.is_done(), {}])
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 220, in reward
    up_angle_hat = self.up_angle_list[self.current_frame]
IndexError: list index out of range
Process Process-12:
Traceback (most recent call last):
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "hurdle_ppo_mp.py", line 180, in worker
    state, reward, is_done, _ = env.step(action)
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 395, in step
    return tuple([self.state(), self.reward(), self.is_done(), {}])
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 220, in reward
    up_angle_hat = self.up_angle_list[self.current_frame]
IndexError: list index out of range
Process Process-6:
Traceback (most recent call last):
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "hurdle_ppo_mp.py", line 180, in worker
    state, reward, is_done, _ = env.step(action)
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 395, in step
    return tuple([self.state(), self.reward(), self.is_done(), {}])
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 220, in reward
    up_angle_hat = self.up_angle_list[self.current_frame]
IndexError: list index out of range
Process Process-2:
Traceback (most recent call last):
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "hurdle_ppo_mp.py", line 180, in worker
    state, reward, is_done, _ = env.step(action)
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 395, in step
    return tuple([self.state(), self.reward(), self.is_done(), {}])
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 220, in reward
    up_angle_hat = self.up_angle_list[self.current_frame]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "hurdle_ppo_mp.py", line 180, in worker
    state, reward, is_done, _ = env.step(action)
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 395, in step
    return tuple([self.state(), self.reward(), self.is_done(), {}])
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 220, in reward
    up_angle_hat = self.up_angle_list[self.current_frame]
Process Process-4:
Traceback (most recent call last):
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "hurdle_ppo_mp.py", line 180, in worker
    state, reward, is_done, _ = env.step(action)
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 395, in step
    return tuple([self.state(), self.reward(), self.is_done(), {}])
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "hurdle_ppo_mp.py", line 180, in worker
    state, reward, is_done, _ = env.step(action)
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 395, in step
    return tuple([self.state(), self.reward(), self.is_done(), {}])
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 220, in reward
    up_angle_hat = self.up_angle_list[self.current_frame]
IndexError: list index out of range
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 220, in reward
    up_angle_hat = self.up_angle_list[self.current_frame]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "hurdle_ppo_mp.py", line 180, in worker
    state, reward, is_done, _ = env.step(action)
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 395, in step
    return tuple([self.state(), self.reward(), self.is_done(), {}])
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 220, in reward
    up_angle_hat = self.up_angle_list[self.current_frame]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "hurdle_ppo_mp.py", line 180, in worker
    state, reward, is_done, _ = env.step(action)
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 395, in step
    return tuple([self.state(), self.reward(), self.is_done(), {}])
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 220, in reward
    up_angle_hat = self.up_angle_list[self.current_frame]
IndexError: list index out of range
Process Process-1:
Traceback (most recent call last):
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "hurdle_ppo_mp.py", line 180, in worker
    state, reward, is_done, _ = env.step(action)
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 395, in step
    return tuple([self.state(), self.reward(), self.is_done(), {}])
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 220, in reward
    up_angle_hat = self.up_angle_list[self.current_frame]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "hurdle_ppo_mp.py", line 180, in worker
    state, reward, is_done, _ = env.step(action)
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 395, in step
    return tuple([self.state(), self.reward(), self.is_done(), {}])
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 220, in reward
    up_angle_hat = self.up_angle_list[self.current_frame]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "hurdle_ppo_mp.py", line 180, in worker
    state, reward, is_done, _ = env.step(action)
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 395, in step
    return tuple([self.state(), self.reward(), self.is_done(), {}])
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 220, in reward
    up_angle_hat = self.up_angle_list[self.current_frame]
IndexError: list index out of range
Process Process-14:
Traceback (most recent call last):
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/genesis/miniconda3/envs/mocap/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "hurdle_ppo_mp.py", line 180, in worker
    state, reward, is_done, _ = env.step(action)
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 395, in step
    return tuple([self.state(), self.reward(), self.is_done(), {}])
  File "/home/genesis/github/mocap/movingcam/control/hurdle/hurdle_env.py", line 220, in reward
    up_angle_hat = self.up_angle_list[self.current_frame]
IndexError: list index out of range

**Comment by kotaxyz** [comment]
this also happens when i try train my own data
